INSERT IGNORE INTO verbs (infinitif, meaning, conjugated, conjugation_link) VALUES
('adorer', 'to adore', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/adorer.html'),
('aider', 'to help', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/aider.html'),
('aimer', 'to love', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/aimer.html'),
('aller', 'to go', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/aller.html'),
('apprendre', 'to learn', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/apprendre.html'),
('arriver', 'to arrive', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/arriver.html'),
('avoir', 'to have', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/avoir.html'),
('compléter', 'to complete', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/compléter.html'),
('cuir', 'to cook', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/cuir.html'),
('demander', 'to ask', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/demander.html'),
('désirer', 'to desire', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/désirer.html'),
('faire', 'to do', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/faire.html'),
('finir', 'to finish', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/finir.html'),
('former', 'to form', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/former.html'),
('habiter', 'to live', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/habiter.html'),
('jouer', 'to play', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/jouer.html'),
('lire', 'to read', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/lire.html'),
('parler', 'to speak', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/parler.html'),
('partir', 'to leave', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/partir.html'),
('passer', 'to pass', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/passer.html'),
('pouvoir', 'to be able to', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/pouvoir.html'),
('prendre', 'to take', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/prendre.html'),
('préférer', 'to prefer', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/préférer.html'),
('regarder', 'to watch', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/regarder.html'),
('résoudre', 'to solve', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/résoudre.html'),
('rêver', 'to dream', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/rêver.html'),
('s''appeler', 'to be called', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/s''appeler.html'),
('se trouver', 'to be located', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/se_trouver.html'),
('travailler', 'to work', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/travailler.html'),
('téléphoner', 'to call', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/téléphoner.html'),
('visiter', 'to visit', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/visiter.html'),
('voir', 'to see', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/voir.html'),
('vouloir', 'to want', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/vouloir.html'),
('épeler', 'to spell', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/épeler.html'),
('étudier', 'to study', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/étudier.html'),
('être', 'to be', FALSE, 'https://leconjugueur.lefigaro.fr/conjugaison/verbe/être.html');
